model:
  use_SkipConnect: False
  use_BN: True
  use_Dropout: False
  dropout: 0.2
  
train:
  epoch: 20
  batch_size: 32
  optimizer: 'adam' # or 'sgd'
  lr: 0.0001
  weight_decay: 0
  sgd:
    momentum: 0.9
  adam:
    beta1: 0.5
    beta2: 0.9

test:
  batch_size: 32
